import Head from 'next/head';
import { useRouter } from 'next/router';
import { GetServerSideProps } from 'next';
import { useState } from 'react';
import { Form, Formik } from 'formik';

import { CircularProgress } from '@mui/material';
import Header from '../../components/Header';
import { useAuth } from '../../hooks/useAuth';
import { fetchLogin, fetchRefreshToken } from '../../helpers/fetchers';
import JWT, { decrypt, encrypt } from '../../helpers/Encrypt';
import {
  setCookieAt,
  setCookieRt,
  destroyCookie,
  parseCookies,
} from '../../helpers/cookie';
import MUIButton from '../../components/UI/MUIButton';
import MUInput from '../../components/UI/MUInput';

interface IUserInput {
  email: string
  password: string
}

function formValidation({ email, password }: IUserInput) {
  const response = {} as IUserInput;
  if (!email.match(/^[\w-.]+@([\w-]+\.)+[\w-]{2,4}$/)) {
    response.email = 'Email Inválido';
  }
  if (password.length <= 5) {
    response.password = 'A senha precisa ter mais que 5 digitos';
  }

  return response;
}

const jwt = new JWT();

export default function Login() {
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);
  const [unauthorized, setUnauthotorized] = useState('');
  const { setEmail } = useAuth();

  const handleClick = async ({ email, password }: IUserInput) => {
    const body = JSON.stringify({
      email,
      password: encrypt(password),
    });

    setIsLoading(true);
    const { acessToken, refreshToken, error } = await fetchLogin(body);

    if (acessToken && refreshToken) {
      setCookieAt('tokenAt', acessToken);
      setCookieRt('tokenRt', refreshToken);
      const { email: jwtEmail } = jwt.decode(acessToken) as { email: string };
      setEmail(jwtEmail);
      router.push('/home');
      setIsLoading(false);
      return;
    }
    setUnauthotorized(error || 'Algum erro ocorreu');
    setIsLoading(false);
  };

  return (
    <div>
      <Head>
        <title>Login - Trybe Social</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <Formik
        initialValues={{
          email: '',
          password: '',
        }}
        validate={formValidation}
        onSubmit={handleClick}
      >
        {() => (
          <Form>
            <MUInput name='email' type="text" label='E-mail' />
            <MUInput name='password' type='password' label='Password' />

            <MUIButton
              type='submit'
              variant='contained'
              bgColor='#44b365'
              size='small'
              disabled={false}
              sx={{
                margin: '0',
                height: '3.4rem',
                textTransform: 'uppercase',
                width: '8rem',
              }}
            >
              {isLoading ? <CircularProgress /> : 'Login'}
            </MUIButton>
            {unauthorized}
          </Form>
        )}

      </Formik>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { tokenRt: encryptRt } = parseCookies(ctx);
  const tokenRt = decrypt(encryptRt);

  if (tokenRt) {
    const { userId } = jwt.verify(tokenRt);
    const { acessToken, refreshToken } = await fetchRefreshToken(
      tokenRt,
      userId,
    );

    if (acessToken && refreshToken) {
      setCookieAt('tokenAt', acessToken, ctx);

      setCookieRt('tokenRt', refreshToken, ctx);
      return {
        props: {},
        redirect: {
          destination: '/home',
          permanent: false,
        },
      };
    }
    destroyCookie('tokenRt', ctx);
  }

  return {
    props: {},
  };
};
