import Head from 'next/head';
import { Fragment } from 'react';

import Header from '../../components/Header';
import { useAuth } from '../../hooks/useAuth';

interface IUser {
  email: string
  firstName: string
  lastName: string
}

export default function MainPage() {
  const { user } = useAuth();

  if (!user) return <div>Loading...</div>

  return (
    <div>
      <Head>
        <title>Profile - Trybe Social</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <h1>Perfil</h1>
      {user && (
        <Fragment>
          <h2>Email: {user?.email}</h2>
          <h2>Nome: {user?.firstName}</h2>
          <h2>Sobrenome: {user?.lastName}</h2>
        </Fragment>
      )}
    </div>
  );
}
