import Head from 'next/head';
import { useEffect, useState } from 'react';

import { createJob, listJobs } from '../../helpers/fetchers';
import Header from '../../components/Header';
import JobItem from '../../components/JobItem';
import { IJob } from '../../helpers/interfaces';
import TrybeModal from '../../components/TrybeModal';
import MUIButton from '../../components/UI/MUIButton';
import { useAuth } from '../../hooks/useAuth';

export default function MainPage() {
  const [jobsList, setJobsList] = useState<IJob[]>([]);
  const { user } = useAuth();
  const [isCreateJobModalOpen, setIsCreateJobModalOpen] = useState(false);

  async function getJobList() {
    setJobsList(await listJobs(user?.accessToken));
  }

  async function postNewJob() {
    await createJob({
      name: '#vqv',
      link: 'https://www.youtube.com/?gl=BR&hl=pt',
    }, user.accessToken);
    await getJobList();
    setIsCreateJobModalOpen(false);
  }

  useEffect(() => {
    getJobList();
  }, [getJobList]);

  if (!user) return <div>Loading...</div>;

  return (
    <div>
      <Head>
        <title>Home - Trybe Social</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <h1>Vagas</h1>
      <MUIButton onClick={() => setIsCreateJobModalOpen(true)}>
        Criar nova Vaga
      </MUIButton>{' '}
      {jobsList.map((data) => (
        <JobItem data={data} key={data.name} />
      ))}
      <TrybeModal
        title='Criar nova Vaga'
        body='Criar nova vagaa'
        onSubmit={postNewJob}
        show={isCreateJobModalOpen}
        setShow={setIsCreateJobModalOpen}
      />
    </div>
  );
}
